### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by BolajiOlajide** [vanesa/kid-o#3]
Hey Vanesa,

I'd like to contribute to this project. Is there anything you'd like me to do?

**Comment by vanesa** [comment]
That would be awesome, thank you! Let me write a script that makes it easier to set everything up locally. I'll get back to you on the details tomorrow or after tomorrow.

**Comment by BolajiOlajide** [comment]
Thanks. I love the work you're doing and it's inspiring. Great.
Looking forward to working with you.

**Comment by BolajiOlajide** [comment]
I'm still waiting on a reply. Just a kind reminder

**Comment by alanhamlett** [comment]
Just to get started, you could:

1. Install [Postgres](https://postgresapp.com/)
2. After cloning the kid-o repo, run these terminal commands:
```
cd kid-o
virtualenv venv -p `which python2` --no-site-packages
source ./venv/bin/activate
pip install -r requirements-frozen.txt
./run.sh
```
3. Create a Postgres user `kido` with password `kido`.
4. Create a Postgres database `kido` with owner `kido`.
5. Go to http://localhost:5000 in your browser to use the app.

**Comment by BolajiOlajide** [comment]
Hey Alan,
Good to see you here. I've done that already. I'm looking in lazy-loading libraries in javascript for the issue raised though.

**Comment by BolajiOlajide** [comment]
<img width="1540" alt="screen shot 2017-08-31 at 12 34 16 am" src="https://user-images.githubusercontent.com/25608335/29899580-382daeea-8de4-11e7-95e0-4cdc5cfc7d6e.png">

Hey, @vanesa @alanhamlett I decided to check out some of the routes and I got this error. I just cloned the project locally and set up my database before. How do I proceed?

**Comment by vanesa** [comment]
@BolajiOlajide @alanhamlett Just pushed an update that should resolve that issue! Forgot to update CSS and JS in that file. Sorry about that!

**Comment by BolajiOlajide** [comment]
I haven't heard from you in a while.
